version: '3.7'

x-node-defaults: &node
  tty: true
  init: true
  image: node:14.21
  entrypoint: ["node"]
  working_dir: /root
  restart: always
  volumes:
    - ./:/root:cached
    - ./node_modules:/root/node_modules:delegated
    - yarn-cache:/.yarn-cache

x-newsletter-command: &newsletter-cmd
  <<: *node
  entrypoint: ["yarn"]
  command: ["dev"]

x-env-defaults: &env
  YARN_CACHE_FOLDER: /.yarn-cache
  NODE_ENV: development
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}
  EMAILX_SERVE_URI: ${EMAILX_SERVE_URI-https://delivery.mindfulcms.com/abmedia/default/compat/email-banner}
  NATIVEX_SERVE_URI: ${NATIVEX_SERVE_URI-https://delivery.mindfulcms.com/abmedia/default/compat/native-email/email-placement}

x-env-virgon: &env-virgon
  <<: *env
  GRAPHQL_URI: ${GRAPHQL_URI-https://graphql.virgon.base.parameter1.com}

services:
  terminal:
    <<: *node
    working_dir: /root
    entrypoint: ["/bin/bash"]
    environment:
      <<: *env

  yarn:
    <<: *node
    working_dir: /root
    entrypoint: ["yarn"]
    environment:
      <<: *env

  all:
    <<: *newsletter-cmd
    working_dir: /root/tenants/all
    environment:
      <<: *env-virgon
      PORT: 80
      EXPOSED_PORT: 22291
      LIVERELOAD_PORT: 32291
      TENANT_KEY: abmedia_all
    ports:
      - "22291:80"
      - "32291:32291"

volumes:
  yarn-cache: {}
